### ISSUE TITLE
ZBXimg for Zabbix 4.2

### ISSUE THREAD

**Issue by Support-Green-IT-Solutions** [celsolom/zbximg#1]
Hi,
Thanks for your script. Have you test it with Zabbix 4.2 ?
Thanks for your response.

**Comment by celsolom** [comment]
Hi! I not tested, but i have checked [Zabbix 4.2 API documentation](https://www.zabbix.com/documentation/4.2/manual/api/reference/image) and nothing is changed. Based on this I believe it works perfectly with version 4.2. I wait your feedback about this. Thanks!
